# set the main lobby using /sw setmainlobby
lobby:
  x:
  y:
  z:
  world:

# the url that appears on the scoreboard
url: "&ewww.example.com"

signsEnabled: true

startLines:
  - "&a&l---------------------------------------------"
  - ""
  - "                              &f&lSkyWars"
  - ""
  - "    &e&lGather resources and equipmenton your island"
  - "      &e&lin order to eliminate every other player."
  - "     &e&lGo to the center island for special chests"
  - "                       &e&lwith special items!"
  - ""
  - "&a&l---------------------------------------------"

disabledCommands: []