main: me.brunorm.skywars.Skywars
version: 0.2.1
name: Skywars
author: BrunoRM
softdepend: [WorldEdit]
api-version: "1.13"

commands:
  skywars:
    description: Main Skywars command.
    aliases: sw
  where:
    description: Tells you where you are.