main: me.brunorm.skywars.Skywars
version: 0.2.8
name: Skywars
author: BrunoRM
softdepend: [WorldEdit, Vault]
api-version: "1.13"

commands:
  skywars:
    description: Main Skywars command.
    aliases: sw
  start:
    description: Starts a Skywars arena game.
  forcestart:
    description: Forces a Skywars arena game to start.
  where:
    aliases: whereami
    description: Tells you where you are.
  leave:
    description: Leave a Skywars arena game.

permissions:
  skywars.*:
    description: Gives access to all Skywars commands.
    children:
    - skywars.admin
    - skywars.config
    - skywars.setmainlobby
    - skywars.forcestart
    - skywars.start
  skywars.admin:
    description: Gives access to admin Skywars commands.
  skywars.config:
    description: Gives access to config subcommand.
  skywars.setmainlobby:
    description: Allows setting the main lobby.
  skywars.forcestart:
    description: Allows using the forcestart subcommand to immediately start a Skywars game.
  skywars.start:
    description: Allows using the start subcommand to start a Skywars game's countdown.