main: me.brunorm.skywars.Skywars
version: 0.2.4.1
name: Skywars
author: BrunoRM
softdepend: [WorldEdit, Vault]
api-version: "1.13"

commands:
  skywars:
    description: Main Skywars command.
    aliases: sw
  start:
    description: Starts a Skywars arena game.
  forcestart:
    description: Forces a Skywars arena game to start.
  where:
    description: Tells you where you are.
  leave:
    description: Leave a Skywars arena game.