# Note:
# Use 1.13+ item IDs
# -------------------

# This is the display name of the kit, used in the kits menu
name: Default kit

# This is the display icon of the kit, used in the kits menu
icon: WOODEN_PICKAXE

# This is the items list that will be given to the player when the game starts
items:
- WOODEN_SWORD
- WOODEN_PICKAXE
- WOODEN_AXE
- WOODEN_SHOVEL
- WOODEN_HOE

# This is the price that will be used when players buy the kit
price: 0
